# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee4fb8a2f442b85cccc888e3c90a2b8b62947f79c5cb86771603a6575a82c6721b07890ea8fc3f706d49140d1cdfdeb8c8e007217e00bd0186241cc76b035e56

test:
  secret_key_base: 6407ffac1788e8b3175c456e51f94da79e7379d3c623954e2a27e115cbbbc0c739b7acac6438fb16ff277c651515701e48d9e71b38fba2833ea0fe018ff1d723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
